# Generated by Django 4.1.4 on 2022-12-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B_name', models.CharField(max_length=30)),
                ('A_name', models.CharField(max_length=25)),
                ('Date', models.DateField()),
                ('B_category', models.CharField(max_length=20)),
            ],
        ),
    ]
