# Generated by Django 4.2.1 on 2023-05-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_issue_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='i_b_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('b_name', models.CharField(max_length=25)),
                ('s_name', models.CharField(max_length=25)),
            ],
        ),
    ]
