# Generated by Django 4.2.1 on 2023-05-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_i_b_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='i_b_data',
        ),
    ]
