# Generated by Django 4.2.1 on 2023-05-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_i_b_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='i_b_data',
        ),
        migrations.AlterField(
            model_name='book',
            name='Date',
            field=models.CharField(max_length=25),
        ),
    ]
