# Generated by Django 4.2.1 on 2023-05-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_delete_i_b_data_alter_book_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='i_b_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('s_name', models.CharField(max_length=25)),
                ('b_name', models.CharField(max_length=25)),
                ('Date', models.CharField(max_length=25)),
            ],
        ),
    ]
