# Generated by Django 4.2.1 on 2023-07-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0011_i_b_data_exp_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='i_b_data',
            old_name='Date',
            new_name='Iss_Date',
        ),
    ]
