# Generated by Django 4.2.1 on 2023-07-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0012_rename_date_i_b_data_iss_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='i_b_data',
            name='Fine',
            field=models.IntegerField(null=True),
        ),
    ]
