# Generated by Django 4.2.1 on 2023-07-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0013_i_b_data_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i_b_data',
            name='Iss_Date',
            field=models.DateField(max_length=25),
        ),
        migrations.AlterField(
            model_name='i_b_data',
            name='exp_date',
            field=models.DateField(max_length=25, null=True),
        ),
    ]
